// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(obj, props) {
    var getter, key, _fn;
    _fn = function(key, getter) {
      return Object.defineProperty(obj, key, {
        configurable: true,
        enumerable: true,
        get: function() {
          var value;
          value = getter.call(this);
          Object.defineProperty(this, key, {
            configurable: true,
            enumerable: true,
            writable: false,
            value: value
          });
          return value;
        }
      });
    };
    for (key in props) {
      getter = props[key];
      _fn(key, getter);
    }
    return obj;
  };

}).call(this);
